### ISSUE TITLE
Is it possible to retrive a App\Entity\User 

### ISSUE THREAD

**Issue by HiroKX** [IDCI-Consulting/IDCIKeycloakSecurityBundle#33]
Hello,

I've successfully implemented the bundle, but I couldn't get any relations of my App\Entity\User. Is there a way to retrieve this?

I've tried with a UserProvider, but something doesn't work properly, I guess...

Thanks for your help.

**Comment by zenobio93** [comment]
Hello @HiroKX,

For our usecase we needed to store / update the user getting by Keycloak into our database.

We have solved this by writing our own KeycloakUserProvider extending the `KnpU\OAuth2ClientBundle\Security\User\OAuthUserProvider` and implementing the `IDCI\Bundle\KeycloakSecurityBundle\Security\User\KeycloakUserProviderInterface`.

Then you can use it as provider:

```
security:
  providers:
    keycloak_security_provider:
      id: App\Core\Security\User\KeycloakUserProvider
      
  firewalls:
    main:
      pattern: ^/
      provider: keycloak_security_provider
```
