### ISSUE TITLE
Installation with composer KO

### ISSUE THREAD

**Issue by adrientiburce** [IDCI-Consulting/IDCIKeycloakSecurityBundle#9]
I started a blank new Symfony 4.3 project to test an implementation of keycloak with this bundle.

But I don't get what I need to do in order to make it working,
I got an error as I run `composer require idci/keycloak-security-bundle`

![image](https://user-images.githubusercontent.com/34744867/63441718-26ceb280-c432-11e9-941d-728d99f1181b.png)

**Comment by Brah0um** [comment]
Hi @adrientiburce 

Thanks for the issue. Is the following file `config/packages/idci_keycloak_security.yaml` generated ??

Could you show its content ?

**Comment by adrientiburce** [comment]
No, it is not generated, only the file `knpu_oauth2_client.yaml` is generated with the following content : 
```
knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
```

Thanks for your help

**Comment by Brah0um** [comment]
The Flex recipe is missing.

To fix the issue simply add the following configuration in `config/packages/idci_keycloak_security.yaml`:

```yaml
# config/packages/idci_keycloak_security.yaml
idci_keycloak_security:
    server_url: 'http://localhost:8080/auth' # your accessible keycloak url
    # server_url: 'http://keycloak.example.com/auth' # example with public url
    realm: 'your-realm'
    client_id: 'your-client-id'
    client_secret: 'your-client-secret'
    default_target_path: 'home' # The route name you will be redirected to after sign in
```

Let me know if it works.

**Comment by adrientiburce** [comment]
Thanks the bundle is now configured, I followed the instructions to edit `security.yaml` and `routes/idci_keycloak_security.yaml`.

When I try to access a secured route the redirection to `http://localhost:8080/auth/realms/<realm-name>/account` works and I'm redirected.

__Issue :__
* When I try to access a secured route, keycloak take into account that I am logged in but I am always redirect to the route specified in `idci_keycloak_security` so I can't access to `/admin`.

* I tried to debug `Keycloakauthenticator.php` and I found out that `supports` method always return `false`.

Is there something else I need to configure in order to make the bundle works ? 
Thanks !

**Comment by Brah0um** [comment]
Can you show me the content of your `security.yaml` file ??

**Comment by adrientiburce** [comment]
I followed the instructions on your `Readme` file juste to have a simple example.
I am not using keycloak with Docker

```yaml
# config/packages/security.yaml
imports:
    - { resource: '@IDCIKeycloakSecurityBundle/Resources/config/security.yaml' } # import our security provider

security:

    firewalls:

        # Authorize everyone to try connecting (this route is imported from our bundle routing configuration)
        auth_connect:
            pattern: ^/auth/connect/.*
            security: false

        # This bundle is using security guard provided by symfony
        # Login form authentication
        secured_area:
             pattern: ^/admin
             guard:
                 provider: idci_keycloak_security_provider
                 authenticators:
                     - IDCI\Bundle\KeycloakSecurityBundle\Security\Authenticator\KeycloakAuthenticator

        # Bearer token authentication
        api:
            pattern: ^/api
            guard:
                provider: idci_keycloak_bearer_security_provider
                authenticators:
                    - IDCI\Bundle\KeycloakSecurityBundle\Security\Authenticator\KeycloakBearerAuthenticator

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/admin, roles: ROLE_USER}
        - { path: ^/api, roles: ROLE_API }
```
